(cl:in-package mini_ros-msg)
(cl:export '(ACTION0-VAL
          ACTION0
          ACTION1-VAL
          ACTION1
          ACTION2-VAL
          ACTION2
          ACTION3-VAL
          ACTION3
          ACTION4-VAL
          ACTION4
          ACTION5-VAL
          ACTION5
          ACTION6-VAL
          ACTION6
          ACTION7-VAL
          ACTION7
          ACTION8-VAL
          ACTION8
          ACTION9-VAL
          ACTION9
          ACTION10-VAL
          ACTION10
          ACTION11-VAL
          ACTION11
          ACTION12-VAL
          ACTION12
          ACTION13-VAL
          ACTION13
))