// Generated by gencpp from file mini_ros/CalibServoResponse.msg
// DO NOT EDIT!


#ifndef MINI_ROS_MESSAGE_CALIBSERVORESPONSE_H
#define MINI_ROS_MESSAGE_CALIBSERVORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mini_ros
{
template <class ContainerAllocator>
struct CalibServoResponse_
{
  typedef CalibServoResponse_<ContainerAllocator> Type;

  CalibServoResponse_()
    : Response()  {
    }
  CalibServoResponse_(const ContainerAllocator& _alloc)
    : Response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Response_type;
  _Response_type Response;





  typedef boost::shared_ptr< ::mini_ros::CalibServoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mini_ros::CalibServoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CalibServoResponse_

typedef ::mini_ros::CalibServoResponse_<std::allocator<void> > CalibServoResponse;

typedef boost::shared_ptr< ::mini_ros::CalibServoResponse > CalibServoResponsePtr;
typedef boost::shared_ptr< ::mini_ros::CalibServoResponse const> CalibServoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mini_ros::CalibServoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mini_ros::CalibServoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mini_ros::CalibServoResponse_<ContainerAllocator1> & lhs, const ::mini_ros::CalibServoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.Response == rhs.Response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mini_ros::CalibServoResponse_<ContainerAllocator1> & lhs, const ::mini_ros::CalibServoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mini_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mini_ros::CalibServoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mini_ros::CalibServoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mini_ros::CalibServoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mini_ros::CalibServoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mini_ros::CalibServoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mini_ros::CalibServoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mini_ros::CalibServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9ca8778f2b24ad03f8213b9fe82be44";
  }

  static const char* value(const ::mini_ros::CalibServoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9ca8778f2b24ad0ULL;
  static const uint64_t static_value2 = 0x3f8213b9fe82be44ULL;
};

template<class ContainerAllocator>
struct DataType< ::mini_ros::CalibServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mini_ros/CalibServoResponse";
  }

  static const char* value(const ::mini_ros::CalibServoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mini_ros::CalibServoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response\n"
"string Response\n"
;
  }

  static const char* value(const ::mini_ros::CalibServoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mini_ros::CalibServoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibServoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mini_ros::CalibServoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mini_ros::CalibServoResponse_<ContainerAllocator>& v)
  {
    s << indent << "Response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINI_ROS_MESSAGE_CALIBSERVORESPONSE_H
