// Generated by gencpp from file mini_ros/CalibServo.msg
// DO NOT EDIT!


#ifndef MINI_ROS_MESSAGE_CALIBSERVO_H
#define MINI_ROS_MESSAGE_CALIBSERVO_H

#include <ros/service_traits.h>


#include <mini_ros/CalibServoRequest.h>
#include <mini_ros/CalibServoResponse.h>


namespace mini_ros
{

struct CalibServo
{

typedef CalibServoRequest Request;
typedef CalibServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalibServo
} // namespace mini_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mini_ros::CalibServo > {
  static const char* value()
  {
    return "c913f1c0a1d31405df8abfbd5898df82";
  }

  static const char* value(const ::mini_ros::CalibServo&) { return value(); }
};

template<>
struct DataType< ::mini_ros::CalibServo > {
  static const char* value()
  {
    return "mini_ros/CalibServo";
  }

  static const char* value(const ::mini_ros::CalibServo&) { return value(); }
};


// service_traits::MD5Sum< ::mini_ros::CalibServoRequest> should match
// service_traits::MD5Sum< ::mini_ros::CalibServo >
template<>
struct MD5Sum< ::mini_ros::CalibServoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mini_ros::CalibServo >::value();
  }
  static const char* value(const ::mini_ros::CalibServoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mini_ros::CalibServoRequest> should match
// service_traits::DataType< ::mini_ros::CalibServo >
template<>
struct DataType< ::mini_ros::CalibServoRequest>
{
  static const char* value()
  {
    return DataType< ::mini_ros::CalibServo >::value();
  }
  static const char* value(const ::mini_ros::CalibServoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mini_ros::CalibServoResponse> should match
// service_traits::MD5Sum< ::mini_ros::CalibServo >
template<>
struct MD5Sum< ::mini_ros::CalibServoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mini_ros::CalibServo >::value();
  }
  static const char* value(const ::mini_ros::CalibServoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mini_ros::CalibServoResponse> should match
// service_traits::DataType< ::mini_ros::CalibServo >
template<>
struct DataType< ::mini_ros::CalibServoResponse>
{
  static const char* value()
  {
    return DataType< ::mini_ros::CalibServo >::value();
  }
  static const char* value(const ::mini_ros::CalibServoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINI_ROS_MESSAGE_CALIBSERVO_H
