# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mini_ros/MiniCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MiniCmd(genpy.Message):
  _md5sum = "83510b9a5f454bd3ceb898b52e349406"
  _type = "mini_ros/MiniCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# motion type: Go, Stop
string motion

# movement type: Stepping, Viewing
string movement

# linear velocity
float32 x_velocity
float32 y_velocity

# angular rate
float32 rate

# viewing params
float32 roll
float32 pitch
float32 yaw

# robot height
float32 z

# Step adjust
float32 faster
float32 slower"""
  __slots__ = ['motion','movement','x_velocity','y_velocity','rate','roll','pitch','yaw','z','faster','slower']
  _slot_types = ['string','string','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motion,movement,x_velocity,y_velocity,rate,roll,pitch,yaw,z,faster,slower

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MiniCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.motion is None:
        self.motion = ''
      if self.movement is None:
        self.movement = ''
      if self.x_velocity is None:
        self.x_velocity = 0.
      if self.y_velocity is None:
        self.y_velocity = 0.
      if self.rate is None:
        self.rate = 0.
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.z is None:
        self.z = 0.
      if self.faster is None:
        self.faster = 0.
      if self.slower is None:
        self.slower = 0.
    else:
      self.motion = ''
      self.movement = ''
      self.x_velocity = 0.
      self.y_velocity = 0.
      self.rate = 0.
      self.roll = 0.
      self.pitch = 0.
      self.yaw = 0.
      self.z = 0.
      self.faster = 0.
      self.slower = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.motion
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.movement
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_9f().pack(_x.x_velocity, _x.y_velocity, _x.rate, _x.roll, _x.pitch, _x.yaw, _x.z, _x.faster, _x.slower))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.motion = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.motion = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.movement = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.movement = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.x_velocity, _x.y_velocity, _x.rate, _x.roll, _x.pitch, _x.yaw, _x.z, _x.faster, _x.slower,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.motion
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.movement
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_9f().pack(_x.x_velocity, _x.y_velocity, _x.rate, _x.roll, _x.pitch, _x.yaw, _x.z, _x.faster, _x.slower))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.motion = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.motion = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.movement = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.movement = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.x_velocity, _x.y_velocity, _x.rate, _x.roll, _x.pitch, _x.yaw, _x.z, _x.faster, _x.slower,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9f = None
def _get_struct_9f():
    global _struct_9f
    if _struct_9f is None:
        _struct_9f = struct.Struct("<9f")
    return _struct_9f
